jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot
security:
  oauth2:
    client:
      registration:
        google:
          client-id: 1035217719453-vbkso2f5leih7s8h3f3pau601icagldc.apps.googleusercontent.com
          client-secret: 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
          scope:
            - email
            - profile